language: node_js
matrix:
  include:
    #################
    # Ubuntu Trusty #
    #################

    - name: "[Trusty] Node.js v6.x"
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
      install: npm install --llnode_build_addon=true
      script: TEST_LLDB_BINARY=`which lldb-3.9` npm run test-all
      node_js: "6"

    - name: "[Trusty] Node.js v8.x"
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
      install: npm install --llnode_build_addon=true
      script: TEST_LLDB_BINARY=`which lldb-3.9` npm run test-all
      node_js: "8"

    - name: "[Trusty] Node.js v10.x"
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
      install: npm install --llnode_build_addon=true
      script: TEST_LLDB_BINARY=`which lldb-3.9` npm run test-all
      node_js: "10"


    ###########################
    # Nightlies & V8 Canaries #
    ###########################

    # Addon is not tested due to lack of node-addon-api
    - name: "[Trusty] Node.js Nightly"
      node_js: "node"
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
      install:
        - npm install --nodedir=$(dirname $(dirname $(which node)))/include/node
      script: TEST_LLDB_BINARY=`which lldb-3.9` npm run test-plugin
      env:
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly

    # Addon is not tested due to lack of node-addon-api
    - name: "[Trusty] Node.js V8 Canary"
      node_js: "node"
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
      install:
        - npm install --nodedir=$(dirname $(dirname $(which node)))/include/node
      script: TEST_LLDB_BINARY=`which lldb-3.9` npm run test-plugin
      env:
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

    ########
    # OS X #
    ########

    - name: "[OSX] Node.js v6.x"
      os: osx
      osx_image: xcode9.3
      install: npm install --llnode_build_addon=true
      script: npm run test-all
      node_js: "6"

    - name: "[OSX] Node.js v8.x"
      os: osx
      osx_image: xcode9.3
      install: npm install --llnode_build_addon=true
      script: npm run test-all
      node_js: "8"

    - name: "[OSX] Node.js v10.x"
      os: osx
      osx_image: xcode9.3
      install: npm install --llnode_build_addon=true
      script: npm run test-all
      node_js: "10"

  # Allow the nightly installs to fail
  allow_failures:

    - node_js: "node"
      sudo: required
      dist: trusty
      env:
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly

    - node_js: "node"
      sudo: required
      dist: trusty
      env:
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary
branches:
  only:
    - master
